tqdm/tqdm

README.md
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

- new-style string formatting (makes tweaking positions of details easier)
- bigger bar to fill 78-column wide terminals
- unicode chars (most terminals support these)
- fractional full blocks for sub-character progress
- docstrings <75 chars so `import tqdm; help(tqdm)` formats with proper linebreaks
- updated tests to reflect changes

Documentation; Pretty output

---

README.md

https://pip.pypa.io/en/latest/reference/pip_install.html#vcs-support
> The "project name" component of the url suffix `egg=<project name>-<version>` is used by pip in its dependency logic to identify the project prior to pip downloading and analyzing the metadata.

#egg to refer to the project name, not the branch name

---

README.md
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Tqdm is great, but it is bound to the iterator, which limits its usage with files and streams read in buffers.
I converted the function tqdm() into a class and it can now be called without an iterable, but I kept a full retrocompatibility (you can still use it directly on an iterator, and trange() also works perfectly well). This change allows to manually call update(n) and close(), so now if you use a buffer and process more than one unit per iteration of loop, you can update your progress bar accordingly.
But to be complete about files, I also added two new arguments:
- unit is a string which will replace the unit "it" in the progress stats.
- unit_scale is a boolean, and if set to True it will reduce the numbers according to the International System of Units and add the corresponding …

Add unit and unit_scale arguments + tqdm is now a class to allow manual update

---

Makefile
tox.ini

Added a new option to the makefile (so users without `nose-timer` installed don't crash when trying to run tests)

tox nose-timer as suggested in #52

---

tqdm/_utils.py

Current code is compatible with Solaris. Just use it.

Solaris ncols compatibility

---

README.rst
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Complement PR #74 to fix #73 and #70.
`tqdm.unpause()` allows to start back where the last printing left off. This is interesting because then we don't need to implement a `pause()` method, nor create any new internal variable. Thus, this should work for all subclasses.
Example:
```
from tqdm import trange
from time import sleep
t = trange(10, leave=True)
sleep(0.5)
t.update()
sleep(0.5)
t.update()
sleep(2) # longer wait time
t.unpause()
sleep(0.5)
t.update()
sleep(0.5)
t.update()
t.close()
```
The rate and ETA should stay stable all along.

Add tqdm.unpause()

---

tqdm/_utils.py

fix for:
File "tqdm\_tqdm.py", line 337, in __init__
TypeError: NoneType is not callable
in IronPython

Fix for IronPython 2.7

---

Makefile
README.rst
setup.py
tox.ini
tqdm/_tqdm.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py

Should fix #59, #100 and #103 by using relative (cpu) timing (`time.process_time()` for Py3.3+ or `time.clock()` for Py2) instead of absolute timing (`time.time()`). This should allow to reliably execute the unit tests that are time dependent, even if the Travis server is suddenly overloaded in the middle of a test.
Signed-off-by: Stephen L. <lrq3000@gmail.com>

relative timing for unit tests (rebased)

---

setup.py

Without this change, the installation via python setup.py install is broken in certain Windows system with encoding set to other than 'utf-8'.
Without specifying the encoding of the README file, the open defaults to system config encoding, which doesn't have to be 'utf-8'. Opening the file in UTF-8 mode fixes that.
Traceback of the error thrown without the fix:
`Traceback (most recent call last):
File "setup.py", line 156, in <module>
README_rst = fd.read()
File "C:\Users\n0272436\Downloads\WinPython-32bit-3.4.3.4\python-3.4.3\lib\encodings\cp1252.py", line 23,
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 17233: character maps to <undefined>
`

Fixed setup.py so that it doesn't throw encoding error.

---

.travis.yml

travis has dropped support for py32, see #112 and:
- https://travis-ci.org/tqdm/tqdm/jobs/103891787
- https://travis-ci.org/tqdm/tqdm/jobs/103908760
Basically the latest version of pip uses the "u" prefix notation for unicode which py32 doesn't like. It's not tqdm's fault so I've left py32 in the tox env list. It's just a Travis environment issue.

Travis Py32

---

README.rst
tqdm/_tqdm.py

It seems that `leave == True` means keep, but old docs say it means remove

update docs about `leave` parameter

---

tqdm/_tqdm.py

Fix issue #144 by providing two variables `rate_noinv` and `rate_noinv_fmt` in `bar_format` to always display the "not inversed" rate.
Also, this PR fix the issue that the `rate` in `bar_format` was always non inversed, whereas it should be inversed when `rate < 1`.

Add no rate inversion option in bar_format

---

tqdm/_tqdm_notebook.py

Should fix issue reported by @wernight in issue #170.
BTW, I noticed a weird issue about old widgets bars reappearing after reloading the notebook, but we can't do anything about it because it seems it's ipywidgets fault. I reported it at https://github.com/ipython/ipywidgets/issues/624.

Fix temporary bar displaying with tqdm_notebook

---

tqdm/tests/tests_main.py

Use sys.executable to run with the same python as the tests are run. Needed for installations with different python installed, e.g. python2 and python3 instead of plain python.

Update test to run with python3 executable

---

README.rst
tqdm/_tqdm.py
tqdm/_tqdm_pandas.py
tqdm/tests/tests_pandas.py

This fixes #182 but this breaks retrocompatibility since `tqdm_pandas` does not accept a bar instance anymore (`tqdm_pandas(tqdm(leave=True))`) but a bar class (`tqdm_pandas(tqdm, leave=True)`).
/EDIT: fixed backwards compatibility.

Fix tqdm_pandas(tqdm_notebook) by delaying instanciation in tqdm_pandas

---

.travis.yml

Trying to make Travis use conda to install pandas instead of building from source via pip. This should dramatically reduce load and time spent (4.2 min - 3.6 min to pip install pandas).
See also discussion at #217 and useful tutorial at [this link](http://sburns.org/2014/03/28/faster-travis-builds.html).

Fix Travis use conda to build pandas instead of pip

---

.travis.yml

Coveralls is currently spamming our PR everytime we commit with duplicate comments containing the exact same info. This seems to have started when we merged #232, more exactly when we started caching pip packages like pandas. The error was reported by @CrazyPython to coveralls devs (https://github.com/lemurheavy/coveralls-public/issues/838) but it was closed and their fix doesn't seem to work.
Plus it reduces build time (~5 sec per python version) plus coveralls sometimes fails and makes the build fail.
Anyway, we use codecov since a while as our main coverage report because it is more stringent (branch coverage for codecov instead of statement coverage for coveralls). So we can safely disable it without losing anything.

Disable coveralls because of duplicate comments on github

---

tqdm/_tqdm_notebook.py

When not run in a notebook, the `sp` is not set. This checks if it is set, and exits cleanly.
The idea is to be able to do something like this (with appropriate catching if interested..):
```python
from tqdm import tqdm, tqdm_notebook
def progressbar(*args, **kwargs):
try:
return tqdm_notebook(*args, **kwargs)
except:
return tqdm(*args, **kwargs)
```
This is a temporary workaround I found useful while waiting for https://github.com/tqdm/tqdm/issues/234

cleaner tqdm_notebook exit when not run in a notebook

---

tqdm/tests/tests_perf.py

Added trick described in https://github.com/tqdm/tqdm/commit/0346a4a19f4cbd7274b1a0bfe12eb54ea71c2319 to the simple bar in perf test. Didn't test if the bar was faster, but since this is exactly the same scenario it should also improve the speed.

Faster simple bar for perf test

---

tox.ini

When running locally, I get:
```
$ make test
...
ERROR: InvocationError: '/Users/peter/PROJECTS/tqdm/.tox/py26/bin/coveralls'
...
ERROR:   py26: commands failed
...
$ /Users/peter/PROJECTS/tqdm/.tox/py35/bin/coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis or CircleCI
```
This fixes that issue.

Ignore coverall failures

---

tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

When running python scripts that use tqdm in cron jobs; i noticed that the output of tqdm is also redirected. I changed the `disable` parameter, so if it is not set explicitly, the output will be disabled automatically if the output file is not a TTY (i.e. is some sort of redirection).

disable automatically on non-TTY

---

README.rst
tqdm/_tqdm.py

alternative to https://github.com/tqdm/tqdm/commit/2d45eca654c805a910bf614bb71b94857ce93778
let me know if this doesn't work @lrq3000

minor optimistaion

---

.gitignore
CONTRIBUTE
Makefile
README.rst
asv.conf.json
benchmarks/benchmarks.py
tqdm/_tqdm.py

Requires the `asv` python package as suggested in #298 (installable via `pip`) and either `conda` or `virtualenv`.
``` sh
~/tqdm$ asv run v1.0.0..master  # all commits from tag v1.0.0 to current master
~/tqdm$ asv publish  # builds html
~/tqdm$ asv preview  # serves to http://127.0.0.1:8080/
```
Takes about 30min to run first time. Pushable to https://github.com/tqdm/tqdm/tree/gh-pages using `asv gh-pages`. See the result here: https://tqdm.github.io/tqdm/ (note: not the same as https://tqdm.github.io/).

initial benchmark framework to visualise regression

---

tqdm/_tqdm.py

Cleaner than removing a commit from master.
Because multiple assignment order is not guaranteed to be concurrency safe depending on the Python interpreter implementation.

Addendum to #288

---

README.rst
examples/simple_examples.py
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

... + Deprecation warning test to get 100% coverage again + Update readme and docstrings to provide more details about these parameters.
Fix regressions spotted in #249 (maxinterval fixing miniters too high) and in #258 (smoothing=0 breaks dynamic_miniters, also old calculation made tqdm faster, so it was reinstated).
Maxinterval would sometimes fix miniters to a value higher than it should, because it was adjusting miniters according to maxinterval instead of mininterval (the other conditions for dynamic_miniters are ok and adjusted better than maxinterval).
Also updated the readme and docstring to give more details on the various interval parameters (mininterval, maxinterval, miniters). They are critical for lots of people and define most of the somewhat weird behaviors of tqdm, so I …

Fix maxinterval to adjust miniters to mininterval + fix dynamic_miniters when smoothing

---

README.rst
tqdm/_tqdm.py
tqdm/_utils.py
tqdm/tests/tests_tqdm.py

Add a `postfix` argument and `set_postfix()` method to supply additional stats to display on the bar, as suggested in #266. The method automatically formats the inputs depending on their datatype. This could be useful for machine learning and for data scientists.
This is an alternative to `set_description()` which asks the user to format themselves the whole description.
Example:
```
from tqdm import trange
from random import random, randint
from time import sleep
t = trange(100)
for i in t:
t.set_postfix(loss=random(), gen=randint(1,999), str='h', lst=[1, 2])
sleep(0.1)
```
Output:
```
98%|9| 98/100 [00:09<00:00,  9.90it/s, loss=0.0419, lst=[1, 2], gen=677, str=h]
```
TODO:

Add set_postfix

---

.coveragerc
examples/7zx.py
setup.py
tqdm/_tqdm.py
tqdm/_utils.py
tqdm/_version.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py
tqdm/tests/tests_version.py

and add branch name in ```__version__``` if available.
This should fix the security issue reported in #328 (thanks to @jwilk!) alias CVE-2016-10075.
TODO (but can be done later, we should merge ASAP a fix for this issue):

Fix security issue in __version__ extra calculation (fix #328)

---

tqdm/_tqdm.py

- inspired by https://github.com/warner/magic-wormhole/issues/158, #76, #344, ....
Fallback to bar width of 10 + unlimited stats width even when `dynamic_ncols=True, ncols=None` and the system terminal has an unknown width.
TODO: possibly consider a hard-coded fallback of `ncols=79 if ncols is None`.

unknown system fix

---

README.rst
examples/redirect_print.py
tqdm/_tqdm.py
tqdm/_tqdm_gui.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_tqdm.py

Implements #275.
`file` argument is now set to None and defined at instanciation inside `__init__()` (instead of at class import). This should ease file redirection (as long as `sys.stdout` is redirected before tqdm instanciation, it should be fine).
TODO:
TODO in a separate PR `resiliency-io-error`:
```python
def move(n):
try:
#...
except IOError as exc:
if not self.resiliency:
raise(exc)
```

Fix `file` default value (ease redirection)

---

tqdm/_main.py

Allows e.g. dashes in the installation path.
fixes #421 #423

CLI: better installation path support

---

.gitattributes
.style.yapf
MANIFEST.in
README.rst
examples/7zx.py
examples/include_no_requirements.py
examples/pandas_progress_apply.py
examples/simple_examples.py
examples/tqdm_wget.py
tqdm/_tqdm.py
tqdm/tests/tests_main.py
tqdm/tests/tests_pandas.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py

documents the availability of {postfix} for the bar_format string and distinguishes where postfix is a string vs dict. Also contrasts postfix behavior from desc/prefix behavior a bit more.
Adds set_postfix_direct method which allows for a keyless value to be added.
Augmentation for
#266 & #270

cleanup doc re: postfix

---

Makefile
README.rst
examples/parallel_bars.py
examples/redirect_print.py
tox.ini
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Implement parallelism safety in `tqdm` by providing a new `set_lock()` class method. This is a follow-up on #291.
For Linux (and any platform supporting `fork`), no action is required from the user.
For Windows, here is the canonical example usage:
```
from time import sleep
from tqdm import tqdm
from multiprocessing import Pool, freeze_support, Lock
def progresser(n):         
text = "bar{}".format(n)
for i in tqdm(range(5000), desc=text, position=n, leave=True):
sleep(0.001)
def init_child(write_lock):
"""
Provide tqdm with the lock from the parent app.
This is necessary on Windows to avoid racing conditions.
"""
tqdm.set_lock(write_lock)
if __name__ == '__main__':
freeze_support()
write_lock = Lock()
L = list(range(10))
Pool(len(L), initializer=init_child, …
```

Parallelism safety (thread, multiprocessing)

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
Makefile
README.rst
examples/redirect_print.py
setup.py
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

+ fixes #459
+ fixes #348
+ fixes #387
+ fixes #398
+ fixes (maybe) #420
+ makes order of the two lines in the loop in https://github.com/tqdm/tqdm/commit/ab1bd789f143b79da7b7c18ba942269afcd7df7d unimportant
+ bug introduced in #317
+ precursor to #399
+ indentation error (fixed in `v4.19.1.post1` on pypi)
+ enumeration warning
+ fixes #331 (from #327). see note below
+ maybe related to #336
Note on #331, regarding https://github.com/tqdm/tqdm/pull/331#issuecomment-272310356, `sp()` can only be used for bar printing/clearing as it keeps track of the last message length. It can't be used in for e.g. `tqdm.write()` as that would set a wrong last message length. Note that `sp()` is still unaware that the last message length may refer to a different nested progress bar, but that can be …

flush on refresh

---

tqdm/_tqdm.py

This fixes the issue I'm having in #398, by making sure that moveto always flushes the control codes it might write to the terminal in order to move the cursor up one or more lines.
Unfortunately I have no idea of how to write a test case for this. The existing test cases still work, though.

always flush after moving the cursor to a different line

---

tqdm/_monitor.py
tqdm/tests/tests_synchronisation.py
tqdm/tests/tests_tqdm.py

Fixes https://github.com/conda/conda/issues/7002 in which `tqdm 4.14.0` is used on a Travis-CI Linux host with Python provided by https://repo.anaconda.com/miniconda/Miniconda2-4.4.10-Linux-x86_64.sh.
At least with Python 2.7, the un`join`ed `TMonitor` threads seem to go rogue when the Python process is terminated. I suspect those threads access some resources that are being unloaded while the process is shutting down, which leads to a segmentation fault.
I did not try it out with the latest version, but at least monkey patched the `TMonitor` from `4.19.8` into `4.14.0` and could still replicate the (very sporadic) segfaults.
I also didn't run the tests locally, so those changes are just a guess -- feel free to correct/alter anything in this PR.
I did not notice any performance impacts, …

Fix TMonitor thread termination

---

README.rst
tqdm/__init__.py
tqdm/_monitor.py
tqdm/_tqdm.py
tqdm/tests/tests_pandas.py

#299 partially achieved its goal. With forbidding `*args`, one can get correct axis now, and use it to get the `total` (as number of iterations in `progress_apply`)
However, pandas sometimes runs several more iterations to optimise itself. For example, in `dataframe.progress_apply(func)`.
- if `func` is a `numpy.ufunc` or is very slow, then it will be executed `total` times.
- but if it is very quick or in some other cases, it will be executed `total+1` or `total+shape[axis0]` times.
I think there is no need to adjust such particular pandas implementation, so in the wrapper function, I write
```python
def wrapper(*args, **kwargs):
t.update(n=1 if t.total and t.n < t.total else 0)
return func(*args, **kwargs)
``` 
if `total` is achieved, `tbar` will not be updated.

fix the problem #299 in terms of using tqdm in pandas

---

tqdm/_tqdm.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_synchronisation.py

Fixes #276 but does not work yet as layout seems to be broken in current ipywidgets (see https://github.com/ipython/ipywidgets/issues/773).
I tried using either `widget.layout.width = 100%` and `Layout(width='100%')`, and in either case `ipywidgets` raises an error saying that both are unknown property/can't import Layout class...

Add ncols to specify tqdm_notebook bar width

---

tqdm/_tqdm.py
tqdm/_utils.py
tqdm/tests/tests_tqdm.py

Fixes #591.
This strips ANSI escape codes from the description string before calculating the remaining length of the bar, such that strings containing e.g. color codes are still displayed with the correct width.

ignore ANSI escape codes in the bar length calculation

---

.gitignore
CONTRIBUTING.md
Makefile
tqdm/_tqdm.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_pandas.py

Fix typo in _tqdm_notebook.py (juputer -> jupyter)

---

.gitignore
CONTRIBUTING.md
Makefile
tox.ini
tqdm/_tqdm.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_pandas.py

1. Drop test cases in python34, and add them for python37
Currently, pandas Officially supports Python 2.7, 3.5, 3.6, and 3.7.
2. Address the future warning in Pandas
In the recent update of Pandas v0.23.0 (May 15, 2018), it says
```
Series.rolling().apply(), DataFrame.rolling().apply(), Series.expanding().apply(), and DataFrame.expanding().apply() have gained a raw=None parameter. This is similar to DataFame.apply(). This parameter, if True allows one to send a np.ndarray to the applied function. If False a Series will be passed. The default is None, which preserves backward compatibility, so this will default to True, sending an np.ndarray. In a future version the default will be changed to False, sending a Series. (GH5071, GH20584)
```
Hence, the test cases of ``test_pandas.py`` will …

address pandas compatibility in test cases

---

MANIFEST.in
setup.py
tqdm.1
tqdm/_main.py

- fixes #460
- fixes #628
- [info](https://github.com/click-contrib/click-man#automatic-man-page-installation-with-setuptools-and-pip)

CLI: add `--man-path` option

---

tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

- Moving locks to class properties
- Adding lazy initialization for multiprocessing locks
Fixes #611 
The current behavior of initializing a multiprocessing lock is undocumented behavior. The main documentation says to feed in a lock explicitly for windows compatibility.
```python
```
Here is how this change affects the following use cases:
- Create a multiprocessing pool, then use tqdm to wrap `pool.imap` or similar methods.
- Write locking will no longer work, since the lock will not exist at the …

Avoid global multiprocessing locks

---

tqdm/_tqdm.py
tqdm/_tqdm_pandas.py

Raise two warnings in `tqdm\_tqdm.py` and `tqdm\_tqdm_pandas.py` that are called but not raised
I work for Semmle and I noticed these issues using our LGTM code analyzer
https://lgtm.com/projects/g/tqdm/tqdm/alerts/?mode=tree&severity=error&ruleFocus=1505923886371
```python
```

Fix warnings that are called but not raised

---

tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

I have hit an issue described in #353 today with what can be boiled down to:
```
In [28]: bool(tqdm.tqdm((1 for i in range(10))))                                                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-e62055aa18f4> in <module>
----> 1 bool(tqdm.tqdm((1 for i in range(10))))
TypeError: 'NoneType' object cannot be interpreted as an integer
In [29]:   import tqdm, sys 
...:   print(tqdm.__version__, sys.version, sys.platform) …
```

tqdm: fix casting to boolean to mimic self.iterable

---

tqdm/_tqdm.py

Jython doesn't have the `multiprocessing` module since, without the GIL, threads can be used more efficiently.
This is a simple change that is avoiding that import and seems to be all that is required to get tqdm work on Jython.
I didn't try the "advanced" stuff and couldn't run tox, but the iterable way seems to be working fine.

Workaround lack of multiprocessing on Jython

---

tqdm/_tqdm.py

This PR superesedes #700. I have tested it against the current `master`.
It fixes the race for `tqdm._instances` between `__init__` and other methods that causes the error `Set changed size during iteration`.
It improves locking around assignments and deletions to `tqdm` class variables. Even though Python guarantees atomicity of individual assignments and deletions, they may be interleaved between threads leading to undesirable results detailed in the second commit message.
---
```python
```

Fix tqdm._instances race and lock assignments to tqdm class variables

---

tqdm/_tqdm_notebook.py

Based on the [documentation](https://github.com/tqdm/tqdm/#parameters), the default value for `file` is `None`. However, if you explicitly provide that as `tqdm_notebook(iterable, file=None)`, you get the "red block". This is a quick little fix for that.
Illustration of problem:
The changes here get rid of that red block.
---
```python
```
```
4.33.0 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] darwin
```
(Didn't see any relevant issues; the fix was so easy that I just made a PR instead of an issue.)
[known issues]: …

Fix tqdm_notebook red block on explicit file=None

---

.meta/.readme.rst
README.rst
tqdm/_tqdm.py
tqdm/_utils.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py

+ `width` := `>0` (fixed), unspecified (auto), `<0` (subtract from auto)
+ `type` := `a` (ascii), `u` (unicode), `b` (blank)
+ takes precedence over `ncols` and `ascii` options
- fixes #623
e.g. for fixed bar width of 10 and right-justified text:
```python
bar_format='{l_bar}{bar:10}|{bar:-10b}some text'
```

add Bar.__format__ helper

---

tqdm/std.py
tqdm/utils.py

I found that passing widechars into `set_description()` would cause the width of description field miscalculated, and break the progress bar.
These are the screen records of [before] and [after] this fix.
[before]: https://photos.app.goo.gl/0JimrcKJklZOSka32
[after]: https://photos.app.goo.gl/2op5CiNpISBk5FHc2

Fix print_status when using widechars in desc

---

tqdm/_main.py
tqdm/_tqdm_gui.py
tqdm/_tqdm_notebook.py
tqdm/_utils.py

```python
```
This makes it much easier to find where in client code needs to be
fixed.
Adds stacklevel kwarg to warnings added in 4.36.0

MNT: set stack level on warnings

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.meta/.readme.rst
README.rst
examples/parallel_bars.py
examples/tqdm_wget.py
tqdm/__init__.py
tqdm/_main.py
tqdm/_monitor.py
tqdm/_tqdm.py
tqdm/_tqdm_gui.py
tqdm/_tqdm_notebook.py
tqdm/_utils.py
tqdm/autonotebook.py
tqdm/gui.py
tqdm/std.py
tqdm/tests/tests_tqdm.py
tqdm/utils.py

- potential future pandas fix (#824)
- better unicode widechar support (#803 -> #410, #805)
- fix example/tqdm_wget unknown total (#826)
- add `stacklevel=2` to warnings (#821)
- misc framework updates
+ snapcraft version fix
+ update issue/pr templates (#830)
+ update unit tests
- misc documentation updates
+ update parallel (multiprocessing, ThreadPoolExecutor) example (#407)
+ add slides, video images
+ add CII Best Practices badge
+ add repology badge
+ update badge icons

next release

---

.meta/.readme.rst
README.rst
examples/redirect_print.py

This adds a `isatty()` method to the `DummyTqdmFile` example. Similar to #439, this makes it a better replacement for `sys.stdout` and `sys.stderr`.
More general thoughts:
* You might want to override `__getattr__` to forward everything except for `write` and `writelines`.
* This should be added to the library, so bugfixes will propagate to all users. Right now, everyone copies the example, so all the copies need to be fixed separately (e.g., hyperopt/hyperopt/pull/496).

Add missing isatty() method to DummyTqdmFile

---

tqdm/std.py

The strings are so short that just using plain dedented literal strings
is just as readable (if not more) than going through dedent(), and this
change saves a call to a not-so-trivial function.
```python
```
```
4.37.0 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] linux
```

Replace dedent calls by dedented strings.

---

README.rst

added from tqdm import tqdm in the first example of Description and additional stats. Required import for working of second part of code.
```python
```

added a missing import

---

.meta/.readme.rst
MANIFEST.in
README.rst
examples/redirect_print.py
examples/tqdm_wget.py
tqdm/contrib/__init__.py
tqdm/std.py
tqdm/tests/tests_tqdm.py
tqdm/utils.py

```python
with tqdm.wrapattr(file_obj, "read", total=file_obj.size) as fobj:
while True:
chunk = fobj.read(chunk_size)
if not chunk:
break
from tqdm.utils import CallbackIOWrapper
with tqdm(total=file_obj.size) as t:
fobj = CallbackIOWrapper(t.update, file_obj, "read")
while True:
chunk = fobj.read(chunk_size)
if not chunk:
break
t.reset()
```
+ [x] inline
+ [ ] readme
```python
pbar = tqdm(total=file_obj.size)
with pbar.self_wrapattr(file_obj, "read") as fobj:
```
with class.method
```python
with tqdm.wrapattr(file_obj, "read", total=file_obj.size) as fobj:
```
- fixes #84

add `wrapattr`

---

.meta/.readme.rst
.travis.yml
CONTRIBUTING.md
MANIFEST.in
README.rst
examples/redirect_print.py
examples/tqdm_wget.py
tqdm/contrib/__init__.py
tqdm/notebook.py
tqdm/std.py
tqdm/tests/tests_tqdm.py
tqdm/utils.py

- officially support `float` for `n` and `total` (#802)
+ `notebook`: use `FloatProgress` <= `IntProgress` (#471, #456)
+ allow imprecision (`n <= total + epsilon`) (#849)
- fix unicode bar format arguments (#803 -> #851)
- add `contrib` submodule (#815)
- add `wrapattr`, `utils.CallbackIOWrapper`, `contrib.DummyTqdmFile` (#84 -> #844)
- update tests
- tidy automatic `snap` deployments
- minor doc update (#854)

next release v4.40.0

---

.meta/.readme.rst
.travis.yml
README.rst
tox.ini
tqdm/keras.py
tqdm/notebook.py
tqdm/std.py
tqdm/tests/tests_keras.py
tqdm/tests/tests_main.py
tqdm/tests/tests_synchronisation.py
tqdm/tests/tests_tqdm.py
tqdm/utils.py

- trim on `ncols` overflow with ANSI handling (#850, #716 <- #690)
- add `notebook.reset()` (#864)
- add `keras.TqdmCallback` (#867 <- #835)
- documentation updates
+ document newly added features (above)
+ notebook `ncols` percentage/pixels (#276)
- test updates
+ test newly added features (above)
+ add CI for `win` and `osx` (#841)
+ `py2` threading

next release v4.41.0

---

tqdm/keras.py

- fixes #869 `keras.TqdmCallback` division errors

fix keras batch_size=None

---

.coveragerc
tqdm/notebook.py
tqdm/std.py
tqdm/tests/tests_notebook.py
tqdm/tests/tests_tqdm.py

As self.sp() is called in other places as well (for example if iterable raises exception), I think it's safer to allow calling it even for disabled instances.

Fix set_description with tqdm.notebook(disable=True)

---

tqdm/contrib/concurrent.py
tqdm/tests/tests_concurrent.py

Allow to set ProcessPoolExecutor.map 'chunksize' argument and provide
sane default value if unset.
+ [x] new feature
```python
```

tqdm.contrib.concurrent.process_map: Add 'chunksize' argument

---

README.rst
tqdm/std.py
tqdm/tests/tests_tqdm.py
tqdm/tqdm.1
tqdm/utils.py

+ [x] add `_screen_shape_wrapper` helper
+ [x] deprecate  `_environ_cols_wrapper`
- fixes #918
Notes:
- uses `dynamic_ncols` in the same way as `ncols` does. This is preferable to creating a new `dynamic_nrows` argument because:
+ feature: it's unlikely that users would want only one to be dynamic
+ performance: if one needs to be dynamic, then it's usually relatively easy to calculate the other too
+ API: it's best to rename `dynamic_ncols` => `dynamic_size` later in v5

add `nrows`

---

README.rst
tqdm/contrib/concurrent.py
tqdm/std.py
tqdm/tests/tests_concurrent.py
tqdm/tests/tests_tqdm.py
tqdm/tqdm.1
tqdm/utils.py

- add `nrows` (#918 -> #924)
- expose and warn about small `chunksize` in `tqdm.contrib.concurrent.process_map` (#912)
- fix py2 file stream comparison (#727 -> #730)
---
- fixes #727 -> closes #730
- fixes #918 -> closes #924
- closes #912

next release v4.44.0

---

tqdm/std.py
tqdm/tests/tests_tqdm.py

Reduces screen flicker/blank space at the cost of ordering.
- continues #924 <- #918, #677

rework `_decr_instances` (nested `close`)

---

tqdm/tests/tests_tqdm.py

Python 3.9 finally removed sys.setcheckinterval().  While the package
apparently tried to account for that, the logic is flawed and the second
getattr() raises an AttributeError even if its result is never used.
This caused tests to fail:
File "/tmp/tqdm/tqdm/tests/tests_tqdm.py", line 126, in pretest
getattr(sys, 'setswitchinterval', getattr(sys, 'setcheckinterval'))(100)
AttributeError: module 'sys' has no attribute 'setcheckinterval'
Refactor the code into a try/except construct that does not execute
the setcheckinterval() branch unless setswitchinterval() is actually
missing.  While at it, scale the arguments a bit -- the current version
used either 100 instructions or 100 seconds that were rather of very
different magnitudes.
python version:
```
3.9.0b1 (default, May 19 2020, …
```

Fix error due to missing sys.setcheckinterval in py3.9

---

.meta/.readme.rst
README.rst
tqdm/contrib/concurrent.py
tqdm/keras.py
tqdm/tests/tests_tqdm.py

- fix missing `sys.setcheckinterval` in py3.9 (#978)
- fix `keras.TqdmCallback` compatibility with `tensorflow==2.2.0` (#979)
+ correct `contrib.concurrent` correct `max_workers` (#977)
+ drop prominent mention of `xrange` (#965)
---
- closes #978
- fixes #979
- fixes #977
- closes #965

next release v4.46.1

---

examples/paper.md

```python
```
References:
* https://jupyter.org/
* https://matplotlib.org/
* https://pandas.pydata.org/
* https://keras.io/

Paper: Spell project names as they spell them

---

examples/paper.bib
examples/paper.md

```python
```
---
Not updated:
* "`tqdm` has accumulated over 20 million downloads [@pypi-downloads]"
* How did you get this value? Would be good to update it.
* "7 thousand libraries [@lib-io]"
* I don't see a count of libraries on https://libraries.io/pypi/tqdm, is it one of these?

Paper: Update impact stats for 2020

---

.coveragerc
.meta/.readme.rst
README.rst
tqdm/cli.py
tqdm/contrib/discord.py
tqdm/contrib/telegram.py
tqdm/contrib/utils_worker.py
tqdm/utils.py

+ [x] fix lazy large memory usage and discard unsent messages
Steps to test:
- `pip install -U 'git+https://github.com/tqdm/tqdm@discord#egg=tqdm'`
- [create a discord bot (not public, no requirement of OAuth2 code grant, only send message permissions) & invite it to a channel](https://discordpy.readthedocs.io/en/latest/discord.html)
- copy the bot token & channel ID and paste below:
```python
from tqdm.contrib.discord import tqdm, trange
for _ in trange(
int(1e8),
token='THIS1SSOMETOKEN0BTAINeDfrOmD1SC0rd',
channel_id=0246813579,
):
pass
```
Result:

add contrib.discord: first Discord Bot!

---

tqdm/autonotebook.py
tqdm/contrib/utils_worker.py

In tqdm.auto, look for `IPython` in `sys.modules` rather than explicitly importing it. If we are in an IPython notebook, then IPython will have already been imported. If we are not in an IPython notebook, then importing IPython will take almost half a second.
Here are import times on a 2018 MacBook Pro with an SSD. Before this patch:
$ time python -c 'from tqdm.auto import tqdm'
real     0m0.474s
user     0m0.278s
sys      0m0.142s
After this patch:
$ time python -c 'from tqdm.auto import tqdm'
real    0m0.069s
user    0m0.041s
sys     0m0.020s
Fixes #709.

Speed up tqdm.auto import when not in an IPython notebook

---

.coveragerc
.meta/.readme.rst
.travis.yml
README.rst
setup.py
tox.ini
tqdm/autonotebook.py
tqdm/cli.py
tqdm/contrib/bells.py
tqdm/contrib/discord.py
tqdm/contrib/telegram.py
tqdm/contrib/utils_worker.py
tqdm/gui.py
tqdm/notebook.py
tqdm/utils.py

- add `contrib.discord` (similar to `contrib.telegram`) (#976)
- add `contrib.bells` to auto-enable all extras
- add `contrib.utils_worker` for common slow tasks (e.g. web I/O)
+ fix lazy large memory usage & discard unsent messages (unprocessed tasks)
- fix slow notebook imports (#955 <- #709)
- fix `gui` `TypeError` on unknown `len()` (#971)
- misc documentation/error message updates
+ more succinct ImportError on missing `ipywidgets` (#872)
+ fix broken/deprecated link (#981)
+ add inline usage for `contrib.discord` and `contrib.telegram`
- misc framework updates
+ add official `py3.8` support (#986)
+ fix `snap` builds
---
- fixes #981
- closes #986
- closes #976
- closes #955
- fixes #709
- fixes #872
- fixes #971
---

next release v4.47.0

---

tqdm/tests/tests_tqdm.py

I fixed test_min_iters().
Previously, the wrong behavior could also pass.
I fixed the code so that I can test the function clearly.
--------
```python
```
> 4.47.0 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
> [GCC 7.5.0] linux

Fix test_min_iters() more clearly

---

tqdm/_monitor.py

This PR fixes a bug in `tqdm_tk` #1006 that prevents using the monitor thread. The thread was holding on to references to Tkinter objects longer than they lived in the main thread, and the `__del__` methods of said objects cannot be called from threads that don't host the `_tkinter.tkapp` instance. This falls afoul of a [known bug](https://bugs.python.org/issue39093) in CPython that I may fix later, and causes the whole interpreter to crash (even at the REPL), but for now this is a correctness issue of tqdm in its own right.
Apologies, but I haven't been able to get the test suite working on my machine so I hope CI will check it out.
+ [X] exception-raising fix
read the [known …

Accidental strongref

---

.github/workflows/bench.yml
.meta/.readme.rst
README.rst
examples/async_coroutines.py
tqdm/_version.py
tqdm/asyncio.py
tqdm/auto.py
tqdm/contrib/__init__.py
tqdm/contrib/bells.py
tqdm/contrib/concurrent.py
tqdm/contrib/discord.py
tqdm/contrib/itertools.py
tqdm/contrib/telegram.py
tqdm/keras.py
tqdm/notebook.py
tqdm/std.py
tqdm/tests/py37_asyncio.py
tqdm/tests/tests_contrib.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py

- fix ANSI escape codes breaking `tqdm.write` (#692, #777)
- fix long-lived strongref (#1007, https://bugs.python.org/issue39093)
- fix cli `--version` crash on missing `git/refs/heads` (#635)
- fix `contrib.tenumerate` ignoring `total` (#1017)
- fix potential deep => shallow `kwargs` copy issues
- improve `notebook` display for unknown `total` (#1015)
- make `asyncio` inherit from `std` rather than `auto`
- make `auto` multi-inherit from `autonotebook`, `asyncio` on Python3.5+
- misc documentation & examples updates
+ mention `docker-compose` requirements (#771)
- misc linting & tidy
- misc minor testing framework updates
---
- fixes #777
- fixes #692
- related #591
- closes #1007
- fixes #771
- fixes #635
- fixes #1017
- fixes #1015

next release v4.48.1

---

README.rst
tqdm/cli.py
tqdm/completion.sh
tqdm/tests/tests_main.py
tqdm/tqdm.1

+ bad idea since there are modes (e.g. `bytes`) which don't do line buffering
---
- fixes #1013

cli: add `--tee`

---

tqdm/std.py
tqdm/tests/tests_tqdm.py

This pull request fixes #689.  Additionally it also adds a progress bar when using the `initial` parameter where previously there was no progress bar at all. See .gifs below for reference.
Before this PR ⬇
After this PR ⬇
Code used in both of the .gifs above
```python
import tqdm
import time
for _ in tqdm.trange(10, initial=90):
time.sleep(0.1)
```
I believe it also fixes #215.
(Github AI please link #215 XD)

fix total ETA when using `initial`

---

.meta/.readme.rst
Makefile
README.rst
tqdm/cli.py
tqdm/completion.sh
tqdm/tests/tests_main.py
tqdm/tqdm.1

+ input passed to `update()`; treated as `float` if needed
+ input passed to `self.n`; treated as `float` if needed
```bash
$ seq 2 2 8642086 | python -m tqdm --total 4321043 | wc -l  # old way
100%|██████████| 4321043/4321043 [00:02<00:00, 2136389.54it/s]
4321043
$ seq 2 2 8642086 | python -m tqdm --total 8642086 --update_to | wc -l  # new way
100%|██████████| 8642086.0/8642086 [00:03<00:00, 2642268.18it/s]
4321043
```
More advanced example (add efficient progress to any other program, even if it's written badly to spam the console with >3 million updates per second):
```bash
$ cat a.c && gcc a.c -o a.out
```
```cpp
#include "stdio.h"
#define TOTAL 1<<23  // prints 0 to 100 with TOTAL increments
int main(){
for(unsigned i=1; i<=TOTAL; i+=2) printf("%.0f\n", i/(double)(TOTAL)*100); }
``` …

cli: add --update and --update_to

---

.meta/.readme.rst
DEMO.ipynb
Makefile
README.rst
examples/tqdm_wget.py
tqdm/cli.py
tqdm/completion.sh
tqdm/gui.py
tqdm/notebook.py
tqdm/std.py
tqdm/tests/tests_main.py
tqdm/tests/tests_tqdm.py
tqdm/tqdm.1

- CLI: add `--tee` (#1014 <- #1013)
- CLI: add `--update` and `--update_to` (#996 <- #975)
- CLI: add `--null` (#996)
- make `update()` return `True` on `display` to ease efficient use of custom callbacks (#845)
- fix `py>=3` CLI `--delim` encoding error
- fix `py>=3.5` version detection in `tqdm.auto` (#1029 <- #1028)
- fix final ETA when using `initial` (#1021 <- #689)
+ add & update custom callback examples
+ improve help formatting of boolean CLI options
- add & update tests
---
- closes #1014
- fixes #1013
- closes #996
- fixes #975
- fixes #845
+ related (but actually opposite) #518
- closes #1029
- fixes #1028
- closes #1021
- fixes #689

next release v4.49.0

---

tqdm/notebook.py

- split bar description into separate widget (fixes #1031)
- improve `reset()`
+ reset bar width if needed
+ reset bar colour
- related #1015
Unfortunately this may break code of a handful of people parsing `tqdm.notebook.tqdm.container.children` since it's changed from `[IProgress(), HTML()]` to `[HTML(), IProgress(), HTML()]`. Technically a breaking change but don't think it affects the vast majority of users.

notebook: fix description width for unknown `total`

---

.github/workflows/check.yml
.meta/.readme.rst
.travis.yml
README.rst
tox.ini
tqdm/_monitor.py
tqdm/notebook.py
tqdm/std.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_synchronisation.py
tqdm/tests/tests_tqdm.py
tqdm/tqdm.1

- fix multiprocessing lock creation leak (#982, #936, #759)
+ fixes #617 which introduced this bug (v4.29.0, released 2019-01-06, undiagnosed until now) where multiple threads could concurrently create and append process locks to a global list, then try to release them without first acquiring :imp:
- major test overhaul: fix, update, and speed up
- misc CI framework updates
- code linting
- minor documentation tidy
----
- fixes #982
- (probably) fixes #936
- fixes #759

next release v4.50.1

---

README.rst
tests/tests_tqdm.py
tqdm/std.py
tqdm/tqdm.1

Closes #1051
Adds the possibility to display ETA date and time. Sample of basic usage of the feature:
```python3
from time import sleep
from random import randint
from tqdm import trange
for i in trange(20, bar_format='{l_bar}{bar}{r_bar} ({eta_dt})'):
sleep(randint(1, 5) / 10)
```
<details>
<summary>How this looks</summary>
</details>
You can also customize the date format with the directives from the `datetime` build-in library (see [the official documentation](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior)):
```python3
from time import sleep
from random import randint
from tqdm import trange
for i in trange(20, bar_format='{l_bar}{bar}{r_bar} ({eta_dt:%Y.%m.%d, %H:%M})'):
sleep(randint(1, 5) / 10)
```
<details>
<summary>How this looks</summary>
</details>
- …

Estimated completion date/time in `bar_format`

---

.coveragerc
.github/CODEOWNERS
.gitignore
.travis.yml
CONTRIBUTING.md
MANIFEST.in
Makefile
README.rst
setup.cfg
setup.py
tests/py37_asyncio.py
tests/tests_asyncio.py
tests/tests_concurrent.py
tests/tests_contrib.py
tests/tests_itertools.py
tests/tests_keras.py
tests/tests_main.py
tests/tests_notebook.py
tests/tests_pandas.py
tests/tests_perf.py
tests/tests_synchronisation.py
tests/tests_tqdm.py
tests/tests_version.py
tox.ini
tqdm/cli.py
tqdm/std.py
tqdm/tests/tests_asyncio.py
tqdm/tqdm.1

- add `{eta}` datetime `bar_format` argument (#1055 <- #1051)
+ e.g. `bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt} [{rate_fmt} ETA:{eta:%y-%m-%d %H:%M}{postfix}]'`
+ add `notebook` argument `display=True` (use `False` with `display(tqdm_object.container)`)
+ add `keras.TqdmCallback` support for initial arguments (use `display=False` with `tqdm_callback_object.display()`)
+ [ ] add documentation
- fix py3 CLI `--update` & `--update_to`
- replace `nosetests` with `pytest` (#1052, #1045)
- add & update tests
----
- closes #1055, fixes #1051
- closes #1059, fixes #909
- closes #1052, closes #1045

next release v4.51.0

---

tqdm/keras.py
tqdm/notebook.py

- allow delaying `display()` to a different notebook cell (#909)
```python
from tqdm.notebook import trange
t = trange(int(1e7), display=False)
```
```python
display(t.container)
for _ in t:
pass
```
- same for `tqdm.keras`
```python
from tqdm.keras import TqdmCallback
...
tqdm_callback = TqdmCallback(..., display=False)
```
```python
tqdm_callback.display()
model.fit(..., verbose=False, callbacks=[tqdm_callback])
```
- support `keras` bar arguments (#1065)
----
- fixes #909
- fixes #1065

notebook: support delay display & other kwargs

---

.github/workflows/check.yml
.github/workflows/comment-bot.yml
.meta/.readme.rst
README.rst
tqdm/asyncio.py
tqdm/contrib/discord.py
tqdm/contrib/telegram.py
tqdm/std.py

- get rid of `get_new` (#1084, #509)
- minor CI framework optimisations
----
- fixes #1084, fixes #509, partially reverts & improves on #1075

next release v4.54.0

---

CONTRIBUTING.md

The "Alternative unit tests with pytest" instructions in CONTRIBUTING.md no longer work after switching from [nose -> pytest](https://github.com/tqdm/tqdm/pull/1052). You need to also install `coverage` and `pytest-cov` in order to run `make alltests`
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]                                                                                           
pytest: error: unrecognized arguments: --cov=tqdm --cov-fail-under=80                                                                                      
```

docs: update the simplified `make alltests` instructions to include reference to installing coverage

---

tests/tests_tqdm.py
tqdm/contrib/discord.py
tqdm/contrib/telegram.py
tqdm/notebook.py
tqdm/std.py

- fix attribute errors when disabled
+ `reset()` (#1125)
+ `unpause()`
- add tests
----
- check for `disable=True` issues
+ [x] std
+ [x] notebook
+ [x] asyncio
+ [x] keras
+ [x] tk
+ [x] gui
+ [x] rich
+ [x] contrib.telegram
+ [x] contrib.discord
- fixes #1125

next release: v4.56.2

---

tests/tests_tqdm.py
tqdm/contrib/__init__.py

Only call `tqdm.write` (which inserts a newline) if
`DummyTqdmFile.write` is itself called with a string containing a
newline; otherwise buffer the rest of the string.
See changes in test_tqdm.py for the patterns this allows.
+ [X] visual output fix
```python
```

`DummyTqdmFile` line buffering

---

tests/tests_tqdm.py
tqdm/std.py

This avoids printing the progressbar for very short loops, i.e. the feature requested in #704.  I am not particularly wedded to the kwarg name, alternatives are welcome.

Allow hiding progressbar until some time interval has elapsed.

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/config.yml
.github/SECURITY.md
CONTRIBUTING.md
benchmarks/benchmarks.py
examples/7zx.py
examples/include_no_requirements.py
tests/tests_main.py
tests/tests_tqdm.py
tox.ini
tqdm/_utils.py
tqdm/notebook.py
tqdm/std.py

- add start `delay` in seconds (#836 <- #1069, #704)
- add tests
- misc code tidy
- misc documentation updates
----
- closes #836
+ fixes #1069
+ fixes #704

next release v4.58.0

---

.meta/.readme.rst
README.rst
benchmarks/README.md
environment.yml
tests/tests_dask.py
tox.ini
tqdm/dask.py
tqdm/gui.py
tqdm/keras.py
tqdm/rich.py

based on `tqdm.keras`
Testing:
`pip install "git+https://github.com/tqdm/tqdm@dask#egg=tqdm"`
```python
from tqdm.dask import TqdmCallback
import dask.array as da
with TqdmCallback(desc="compute"):
x = da.random.random((10000, 10000), chunks=(1000, 1000))
y = x + x.T
z = y[::2, 5000:].mean(axis=1)
z.compute()
```
```python
from tqdm.dask import TqdmCallback
import dask.array as da
cb = TqdmCallback(desc="global")
cb.register()
x = da.random.random((10000, 10000), chunks=(1000, 1000))
y = x + x.T
z = y[::2, 5000:].mean(axis=1)
z.compute()
```
----
- fixes #278
- replaces/closes #279

add `dask` submodule

---

tests/py37_asyncio.py
tqdm/asyncio.py
tqdm/auto.py

tqdm's as_completed() is helpful, but does mean results are not in the same order as inputs, which can be frustrating.
I've tried writing a wrapper which emulates the behaviour of asyncio.gather, though I'm not sure whether this conforms to the ideas of the project. (I'm not sure the `typing` import will be well appreciated, at the very least)

Adding an asyncio.gather() replacement for tqdm

---

tests_notebook.ipynb
tqdm/notebook.py

If you specify a delay in a jupyter notebook, the bar will always display regardless.
This PR will also delay the `display` command until the first update, unless display=True.

notebook: support `delay`

---

tests/tests_contrib.py
tqdm/contrib/__init__.py

There's currently the issue that `tqdm_class` cannot be passed to `tmap` and `tzip`. This PR fixes the issue and adds tests for it. 
Here's a repex of the problem: 
```python
from tqdm.contrib import tmap
from tqdm import tqdm       
list(tmap(print, range(10), tqdm_class=tqdm))
```
```pytb
---------------------------------------------------------------------------
TqdmKeyError                              Traceback (most recent call last)
<ipython-input-4-62e01f8ad3b6> in <module>
----> 1 list(tmap(print, range(10), tqdm_class=tqdm))
~/anaconda3/lib/python3.7/site-packages/tqdm/contrib/__init__.py in _tmap(function, *sequences, **tqdm_kwargs)
64     tqdm_class  : [default: tqdm.auto.tqdm].
65     """
---> 66     for i in _tzip(*sequences, **tqdm_kwargs):
67         yield function(*i)
68 …
```

Fix that tqdm_class cannot be passed to `tmap` and `tzip`

---

.meta/.readme.rst
README.rst
tests/contrib/tests_logging.py
tests/tests_contrib_logging.py
tqdm/contrib/logging.py

this implements a slightly improved version of #786
The solution mainly differs from the one outlined in #786 in the following ways:
- multiple `loggers` can be specified (still optional, and probably not needed most of the time)
- a `tqdm` class can be passed in
- Python 2 support

added logging sub-module

---

tests/tests_keras.py
tqdm/keras.py

This fix `TqdmCallback` showing wrong information about epochs when resume training with `initial_epoch != 0`  as was reported on #1138 
The test has been provided but also the Colab example provided by @fabiocarrara  [here](https://colab.research.google.com/drive/1WMKllAs_edpU_kAV9klYk7q1lsP9DXwm?usp=sharing):

fix Display wrong epoch on Keras resume training

---

tqdm/utils.py

This is related to https://github.com/conda/conda/issues/10673 where tqdm is used internally and a user reported an error with the `_screen_shape_linux` function.

Gracefully handle empty COLUMNS/LINES env vars on Linux.

---

.github/workflows/comment-bot.yml
.meta/.readme.rst
README.rst
tqdm/utils.py

- fix `utils._screen_shape_linux()` sometimes raising `ValueError` (#1174)
- minor build/CI framework updates
- minor documentation updates
- fix typo (#1178)
- link to [merch](https://tqdm.github.io/merch)! :billed_cap: :shirt:
----
- closes #1174
+ related conda/conda#10673
- closes #1178

next release v4.61.1

---

tqdm/contrib/telegram.py
tqdm/rich.py

Add an option for delete bar message with the _**deleteMessage**_ method in Bot API.

telegram: add `delete()` when `leave=False`

---

.github/workflows/test.yml
.meta/.readme.rst
DEMO.ipynb
README.rst
setup.cfg
tqdm/asyncio.py
tqdm/contrib/telegram.py
tqdm/keras.py
tqdm/rich.py
tqdm/std.py

- install `colorama` on Windows (#1139, #454)
- add telegram support for `leave=False` (#1189)
- support `pandas==1.3.0` (#1199)
- fix `keras` potential `AttributeError` (#1184 <- #1183)
- fix py3.10 `asyncio` tests (#1176)
- flush `stdout`/`err` before first render (#1177)
----
- fixes #1139
+ fixes #454
- closes #1189
- fixes #1199
- closes #1184
+ fixes #1183
- fixes #1176
- fixes #1177

next release v4.61.2

---

tests/py37_asyncio.py
tqdm/asyncio.py

Intended as a drop-in replacement of the stdlib `asyncio.gather()`, it would be much reasonable if the function interface is consistent with that of `asyncio.gather()` as well.
It also ensures that our interface doesn't violate the least-surprising principle. It would have been surprising and frustrating for a user to wanting to use `tqdm_asyncio.gather()` as a drop-in replacement to the stdlib `asyncio.gather()` but ending up being bitten by the trivial inconsistency.

`asyncio.gather` API consistency with stdlib

---

tests/tests_contrib_logging.py
tqdm/contrib/logging.py

When using the logging redirection, logs will currently always be printed
to stdout, while the logging module default is to print to stderr.
Fix this by trying to inherit the stream from the existing handler, like
the code already does for the formatter.
Consider the following example:
import logging
import time
from tqdm.contrib.logging import tqdm_logging_redirect
log = logging.getLogger()
log.warning("start")
with tqdm_logging_redirect(range(int(4))) as pbar:
for i in pbar:
time.sleep(0.1)
log.warning(f"Step {i}")
log.warning("done")
Running this while redirecting stdout (`$ python3 log.py > /dev/null`)
without this patch will print:
$ venv/bin/python log.py > /dev/null
start
100%|████████████████████████████████████████████| 4/4 [00:00<00:00,  9.87it/s]
done
After this patch:
$ …

logging: inherit output stream from existing handler

---

tqdm/utils.py

This PR fixes a PermissionError on Windows when deleting objects caused by the reference cycle in `DisableOnWriteError`. The solution is to wrap the tqdm instance in `weakref.ref` in `DisableOnWriteError.disable_on_exception` to break the cycle.

Use weakref on tqdm instance in DisableOnWriteError

---

tests/tests_contrib_logging.py
tox.ini
tqdm/contrib/__init__.py
tqdm/contrib/bells.py
tqdm/contrib/concurrent.py
tqdm/contrib/discord.py
tqdm/contrib/itertools.py
tqdm/contrib/logging.py
tqdm/contrib/telegram.py
tqdm/contrib/utils_worker.py
tqdm/utils.py

- `contrib.logging`: inherit existing handler output stream (#1191)
- fix `PermissionError` by using `weakref` in `DisableOnWriteError` (#1207)
- fix `contrib.telegram` creation rate limit handling (#1223, #1221 <- #1220, #1076)
- misc tidy: relative imports
----
- closes #1191
- closes #1207
- fixes #1220
- closes #1223
- fixes #1076
- replaces/closes #1221

next release v4.62.1

---

tqdm/contrib/concurrent.py

fix `contrib.concurrent` with generators

---

tqdm/contrib/concurrent.py
tqdm/notebook.py

- fix notebook memory leak (#1216)
- fix `contrib.concurrent` with generators (#1233 <- #1231)
----
- fixes #1216
- closes #1233
+ fixes #1231

next release v4.62.2

---

.github/workflows/check.yml
.github/workflows/test.yml
.pre-commit-config.yaml
Makefile
setup.cfg
tests/tests_main.py
tests/tests_tqdm.py
tox.ini
tqdm/autonotebook.py
tqdm/cli.py
tqdm/notebook.py
tqdm/std.py

- add `__reversed__()`
- add efficient `__contains__()`
- improve CLI startup time (replace `pkg_resources` => `importlib`)
- `tqdm.autonotebook` warning & `std` fallback on missing `ipywidgets` (#1218 <- #1082, #1217)
- warn on positional CLI arguments
- misc build/test framework updates
+ enable `py3.10` tests
+ add `conda` dependencies
+ update pre-commit hooks
+ fix `pytest` config (`nbval`, `asyncio`)
+ fix dependencies & tests
+ fix site deployment
----
- closes #1218
- fixes #1082
- fixes #1217

next release v4.63.0

---

tqdm/std.py

The recent commit 63f427b0b8be2102bcc8251d7548e0f51b81f00e (which was evidently in response to #1177) is leading to errors in some cases.  It turns out that `sys.stdout` and `sys.stderr` can be `None` in some cases, as mentioned in the note at the bottom of [this section](https://docs.python.org/3.9/library/sys.html#sys.__stdin__) in the python docs.  (This is news to me, and the cases I've encountered this in are not like what the docs suggest.)  When they are `None` [an error occurs inside `tqdm`](https://github.com/sxs-collaboration/sxs/runs/3588413424?check_suite_focus=true#step:7:67) because obviously `None.flush()` does not exist.
This PR just checks that `stderr` and `stdout` actually have a `flush` attribute before using that attribute.  Note that we can't just reuse `fp_flush` …

Ensure that stderr/stdout has flush attr before calling it

---

.meta/.readme.rst
README.rst

Small typo fix in custom callback code example.
Thanks for this amazing library, btw!

docs: fix custom callback example typo

---

tqdm/autonotebook.py

There's no reason to block autonotebook in vscode anymore since vscode-jupyter supports ipywidgets just fine (for almost a year now?).
Closes #1213

autonotebook: re-enable VSCode

---

.meta/.readme.rst
README.rst
environment.yml
tqdm/autonotebook.py
tqdm/rich.py
tqdm/std.py

- `rich`: expose `options` kwargs (#1282)
- `autonotebook`: re-enable VSCode (#1309)
- build: fix dev deps URL
- docs: fix typos (#1301, #1299)
---
- replaces/closes #1282
- closes #1309
- closes #1301
- closes #1299

next release v4.63.2

---

.meta/.readme.rst
README.rst
environment.yml
setup.cfg
tqdm/contrib/bells.py
tqdm/contrib/discord.py
tqdm/contrib/slack.py

```python
>>> from tqdm.contrib.slack import trange
>>> for _ in trange(100, token='{token}', channel='{channel}'):
...     ...
```
* `{token}` is a long code, usually prefixed with `xoxb-`
* `{channel}` can be either a channel name prefixed with a [hash](https://en.wikipedia.org/wiki/Number_sign) or a channel identifier
Use this [manifest](https://api.slack.com/reference/manifests#fields) to [create an app](https://api.slack.com/authentication/basics#creating):
```yml
display_information:
name: tqdm
features:
bot_user:
display_name: tqdm
oauth_config:
scopes:
bot:
- chat:write.public
- chat:write
```
Note that the [`chat:write.public`](https://api.slack.com/scopes/chat:write.public) scope is only required to send messages to channels the app isn't member of.

add contrib.slack

---

pyproject.toml

Fix `pyproject.toml` to exclude the `examples` directory from being installed as a top-level package.

build: do not install `examples` package

---

.github/workflows/test.yml
.meta/.readme.rst
CONTRIBUTING.md
README.rst
asv.conf.json
examples/async_coroutines.py
examples/parallel_bars.py
tests/tests_asyncio.py
tests/tests_utils.py
tox.ini
tqdm/notebook.py
tqdm/std.py
tqdm/utils.py

- fix `utils.envwrap` types (follow-up to #1491, fixes #966, fixes #1319, closes #1320)
+ e.g. cloudwatch & kubernetes workaround: `export TQDM_POSITION=-1`
- drop mentions of unsupported Python versions

fix `envwrap` types, update docs

---

tqdm/notebook.py

The progress bar in Jupyter was misaligned (jumping when the number of digits changes) because html escape eats simple spaces. Replacing with UTF "Figure Space".

fix HTML-escaped space padding in notebook

---

tqdm/keras.py

when `verbose==2`, TqdmCallback object does not define `batch_bar` inside `__init__` but only in `on_epoch_begin`.
If `keras.model.fit` is run after all training epochs are finished, `on_train_end` throws error because `self.batch_bar` does not exist.
Fix is to check if batch_bar attribute exists before closing it, similar to how it is handled inside `on_epoch_begin`.

fix: keras.TqdmCallback: batch_bar does not always exist on_train_end

---

tqdm/std.py

This PR fixes the DeprecationWarning that is raised when using `datetime.datetime.utcfromtimestamp` in Python 3.12.
In the `tqdm/std.py` file:
- Changed the import statement from `from datetime import datetime, timedelta` to `from datetime import datetime, timedelta, timezone`.
- Replaced `datetime.datetime.utcfromtimestamp(0)` with `datetime.datetime.fromtimestamp(0, datetime.timezone.utc)`.
This PR fixes issue [#1517]: "Use of datetime.datetime.utcfromtimestamp shows DeprecationWarning in Python 3.12".
The changes have been tested on Python 3.12 and the warning is no longer raised.
Fixes [#1517]

Fix DeprecationWarning for datetime.utcfromtimestamp in Python 3.12

---

tqdm/rich.py

See how I've come to this conclusion. This note and notes before it:
- https://github.com/tqdm/tqdm/issues/1306#issuecomment-1322762835
Testcase:
```py
from tqdm.rich import trange, tqdm
for i in trange(10):
print(f"i={i}")
print("finished")
```
This snippet, when run, must reach 100%. without the patch it doesn't even get past 0.
The `display()` calls in std.close are never reached because the "gui mode check" exits the function:
- https://github.com/tqdm/tqdm/blob/6791e8c5b3d6c30bdd2060c346996bfb5a6f10d1/tqdm/std.py#L1295-L1297

Fix: Add display() call to close() in rich module

---

.meta/.readme.rst
.pre-commit-config.yaml
DEMO.ipynb
README.rst
tests/tests_tqdm.py
tqdm/asyncio.py
tqdm/contrib/__init__.py
tqdm/contrib/discord.py
tqdm/contrib/logging.py
tqdm/contrib/slack.py
tqdm/contrib/telegram.py
tqdm/dask.py
tqdm/gui.py
tqdm/notebook.py
tqdm/rich.py
tqdm/std.py
tqdm/tk.py
tqdm/utils.py

- `rich`: fix completion (#1395 <- #1306)
- minor framework updates & code tidy

next release v4.66.4

---

.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
asv.conf.json
environment.yml
pyproject.toml
tox.ini
tqdm/utils.py

- utils: support `ncols` auto-detection on FreeBSD (https://github.com/casperdcl/git-fame/issues/98)
- add official Python 3.12 support
- docs
+ bump `pydoc-markdown` (work-around for https://github.com/NiklasRosenstein/pydoc-markdown/issues/329)
+ bump `jsmin` (work-around for https://github.com/tikitu/jsmin/pull/44)
- bump `flake8`

misc framework updates

---

tqdm/cli.py

Fix docstring processing code to reindent the docstrings if using Python 3.13 or newer.  Starting with this version, all docstrings are automatically dedented by Python, which causes the regular expression to fail to match.
Fixes #1585

cli: Fix docstring processing with Python 3.13+

---

tests/tests_asyncio.py

See https://github.com/python/cpython/issues/117536#issuecomment-2036883124
Built on https://github.com/tqdm/tqdm/pull/1594
---
This makes the warning go away. However, perhaps `tqdm.close()` should try awaiting `self.iterable.aclose()` if it exists and is awaitable -- that way callers won't need to do that.
Let me know if you prefer that and I can propose an alternate PR.

Avoid Python 3.13+ RuntimeWarning: coroutine method 'aclose' of 'acount' was never awaited

---

pyproject.toml
tqdm/contrib/discord.py

This PR is an alternative to PR #1383 with the preserved functionality of choosing to which `channel_id` to post the progress bar preserved. This is entirely built up on Discord REST API and requires no additional packages to run. This is analogous to the Telegram contrib.

`tqdm.contrib.discord`: replace `disco-py` with `requests`
