Makefile
README.md
setup.py
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Efficiency

---

.travis.yml

Add flag to travis file to switch to container based infrastructure

---

README.md
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Feel free to merge if no more iterations are needed.

Add option to disable progress bar

---

Makefile
README.md
examples/simple_examples.py
examples/tqdm_wget.py
tqdm/_tqdm.py

Simple iterator decorators and stand-alone basic version of `wget`

added examples folder, minor documentation fixes

---

README.rst
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Min update

---

Makefile
README.rst
examples/simple_examples.py
tox.ini
tqdm/_tqdm.py
tqdm/_utils.py

dynamic ncols (eg on widow resize)

---

README.rst
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py
tqdm/tests/tests_version.py

Exponentially weighted moving average, tests, documentation

---

.travis.yml
Makefile
setup.py
tox.ini
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py

basic performance test, flake8 coverage for tests

---

README.rst
tqdm/_tqdm.py
tqdm/_utils.py
tqdm/tests/tests_tqdm.py

Fix #62 and https://github.com/noamraph/tqdm/issues/16.
This allows to do this:
And even this:

Nested progressbars

---

README.rst

Update the Readme with a Usage chapter and a detailed example on how to make a good progress bar.

Readme examples

---

tqdm/__init__.py
tqdm/_tqdm.py
tqdm/_tqdm_gui.py
tqdm/tests/tests_tqdm.py

Inheritability

---

tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Negative Updates raise error

---

README.rst

Add link to changelog in README.rst

---

tqdm/_utils.py

Partially revert "forcefully detect ascii fallback" to fix multibar positioning error
Addresses #130

Position error regression bugfix

---

tqdm/_utils.py

MSYS added to environ_cols

---

README.rst
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Rebased and fixed as per #138 , #148

Print message 2

---

tqdm/_tqdm.py
tqdm/_tqdm_notebook.py

fixes import warnings related to ipython

notebook warning suppression, flake8

---

README.rst
RELEASE
tqdm/__init__.py
tqdm/_main.py
tqdm/tests/tests_main.py
tqdm/tests/tests_tqdm.py

custom POSIX-style CLI pipe delimeter support as per #161

Cli delims

---

README.rst
examples/pandas_progress_apply.py
tqdm/_tqdm_pandas.py
tqdm/tests/tests_pandas.py

pandas.DataFrame.apply support

---

README.rst
tqdm/_tqdm_gui.py
tqdm/_tqdm_notebook.py

Fix #169, and also fix a similar issue with tqdm_gui. Also updated README.rst to implement #164.

Add tqdm_notebook.write() and fix tqdm_gui.write().

---

tqdm/_tqdm_pandas.py
tqdm/tests/tests_pandas.py

pandas series support '

---

tqdm/_tqdm_notebook.py

attempt to fix aliased imports as per #187

IPython aliased imports fix

---

tqdm/_tqdm.py

Should fix #193.
Maybe should add a unit test for threads? (but is that really that useful?)

Fix tqdm.write() when not yet instanciated

---

README.rst

Mono space

---

README.rst
examples/pandas_progress_apply.py
tqdm/_tqdm.py
tqdm/tests/tests_pandas.py

pandas.Series.progress_map, update docs, tests

---

README.rst

Add note and link to bpython. See #216.

Update README.rst with screenshot caption

---

tqdm/_tqdm.py
tqdm/_tqdm_gui.py
tqdm/_utils.py

Removed commented-out code

---

tqdm/_tqdm.py

* Fix `time()` call in `tqdm.refresh()` -> `self._time()`
* Try to avoid racing conditions in `write()` per #261

Fix time() in refresh() + avoid racing conditions in write()

---

tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

Both `refresh` and `clear` would fail if the bar was disabled

fixed refresh() and clear() if disabled

---

README.rst
examples/include_no_requirements.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_main.py
tqdm/tests/tests_tqdm.py

partially inspired by https://www.codacy.com/app/tqdm/tqdm

Style fixes

---

README.rst
tqdm/_main.py
tqdm/tests/tests_main.py

CLI --bytes

---

.travis.yml
tox.ini

Reorder Travis dependencies install to fix numpy install

---

.mailmap
.travis.yml
Makefile
examples/7zx.py
tox.ini
tqdm/_main.py
tqdm/_utils.py
tqdm/tests/tests_perf.py

uncompression (compressed archive extraction)

---

tqdm/_tqdm.py

fix monitor delete race

---

tqdm/_tqdm.py
tqdm/_version.py

Fixes the fact that [this comment (tqdm/_tqdm.py#L404)](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L404) was not addressed. (`self` should not be in `cls._instances` if `position` was manually specified). Not sure if this breaks something else - all unit tests pass.
This fixes the [example suggested](https://github.com/tqdm/tqdm/issues/384#issuecomment-302973641) in #384, and possibly #285, #329.

fix manually positioned nested bars clearing

---

README.rst
examples/tqdm_wget.py
tqdm/_tqdm.py

closes #354 binary unit prefixes

unit_divisor, allowing e.g. 1024

---

tqdm/_tqdm.py

Right now file is set after the `isatty` check.

Set file before trying to read attr's

---

README.rst
tqdm/_tqdm.py
tqdm/tests/tests_main.py
tqdm/tests/tests_pandas.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py
tqdm/tests/tests_version.py

- supercedes #273 (credit: @lrq3000)
- fixes #295 (credit: @zyddnys)
- note: would not quite make #354/#356 redundant

add numeric support for unit_scale

---

tqdm/_tqdm.py

local copy of #426 
TODO: fix py3.6

Added contextmanager to disable tqdm and allow smooth write to stdout

---

README.rst
tqdm/_tqdm.py
tqdm/tests/tests_tqdm.py

+ [x] avoid over printing (~~use `update(0)`~~ allows `refresh=False`)

set_description() and set_postfix() call refresh()

---

tqdm/_tqdm.py
tqdm/tests/tests_perf.py
tqdm/tests/tests_tqdm.py

A fix for the problem that tqdm does not work on Aws Lambda
https://github.com/tqdm/tqdm/issues/466

Fix Lock NotImplementedError, use RLock

---

tqdm/__init__.py
tqdm/_monitor.py
tqdm/_tqdm.py

- raise `TqdmMonitorWarning` and continue upon `TMonitor` creation errors
- fixes #522

TMonitor warnings

---

.mailmap
CONTRIBUTING.md
README.rst
examples/7zx.py
tqdm/__init__.py
tqdm/_main.py
tqdm/_tqdm.py
tqdm/_tqdm_gui.py
tqdm/tests/tests_tqdm.py

- fix #532 `write()` with manual `position`
+ more robust free position finding
+ TODO: better instance removal reordering
- add `TqdmWarning` base class
- unit tests
- fix GUI `__del__()`
+ add `TqdmExperimentalWarning`
- add, tidy & fix unit tests
- document wiki release notes & update contributors

`write()` and synchronisation improvements

---

tqdm/_main.py
tqdm/_tqdm.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_pandas.py
tqdm/tests/tests_synchronisation.py

@casperdcl 
I think here it should be a warning, because normally total should be automatically computed by tqdm. and only a few cases need manually set total. Like this:

Add `total` support to `tqdm.pandas()`

---

tqdm/_main.py
tqdm/_tqdm.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_pandas.py
tqdm/tests/tests_synchronisation.py

fixes #530.
Add a progress_bar without `total` (see #530 for reason).
Maybe should add some documents.
TODO:

Add progress_apply for pd.(Series|DataFrame).(rolling|expanding)

---

README.rst

Add missing import in example

---

tqdm/_tqdm.py

- closes #544 (alternative PR)
- closes #510 (duplicate)

solve synchronisation `AttributeError` issues during instantiation

---

.gitignore
CONTRIBUTING.md
Makefile
tox.ini
tqdm/_tqdm.py
tqdm/_tqdm_notebook.py
tqdm/tests/tests_pandas.py

in the function ``__iter__``, the variable ``smoothing`` may not be written back to the ``self`` object, which causes the issue #566.
This PR fix the problem by fixing a bug found by @simonm3 in #566.
Maybe helpful for #449

fix smoothing bug

---

tqdm/_tqdm.py

Make sure _lock exists during write()

---

.meta/.readme.rst
.travis.yml
CODE_OF_CONDUCT.md
README.rst
examples/redirect_print.py
tqdm/std.py
tqdm/tests/tests_pandas.py

- add `pandas` builtin operations check (#843 <- #697)
- avoid unnecessary `dedent` (#837)
- remove unneeded bar logic
+ document default argument overriding (#370)
+ add missing `isatty()` (#713)
+ update badges
+ add code of conduct
- update framework
+ clean CI stages
+ update CI default `py3.6` => `py3.7`
+ automate snap releases (#686 <- #685)

next release v4.39.0

---

tqdm/std.py
tqdm/tests/tests_pandas.py

fix unhashable pandas arguments

---

tqdm/std.py
tqdm/tests/tests_tqdm.py
tqdm/utils.py

- closes #716
- fixes #690
- related to #623
- helps avoid #630

trim on overflow

---

.meta/.readme.rst
README.rst
tox.ini
tqdm/keras.py
tqdm/tests/tests_keras.py

Official `keras` callback
+ [x] epochs
+ [x] batches
+ [x] double-check automation & syntax
+ [ ] update framework & CI tests
- fixes #835

keras callback

---

.meta/.readme.rst
.travis.yml
Makefile
README.rst
examples/include_no_requirements.py
examples/pandas_progress_apply.py
examples/parallel_bars.py
examples/tqdm_wget.py
examples/wrapping_generators.py
tox.ini
tqdm/contrib/__init__.py
tqdm/contrib/concurrent.py
tqdm/contrib/itertools.py
tqdm/keras.py
tqdm/notebook.py
tqdm/tests/tests_concurrent.py
tqdm/tests/tests_contrib.py
tqdm/tests/tests_itertools.py
tqdm/tests/tests_keras.py
tqdm/tqdm.1

- `notebook`: update `disable=None` behaviour (#880)
- `tqdm.keras`: support `tensorflow.keras` as well as `keras` (#885)
- add `contrib` (#882)
+ `tenumerate` (#840 <- #480, #402)
+ `tzip` <= `zip`
+ `tmap` <= `map`
+ add `concurrent` module
* `thread_map` <= `concurrent.futures.ThreadPoolExecutor.map`
* `process_map` <= `concurrent.futures.ProcessPoolExecutor.map`
+ add `itertools` module (#225) stub
* `product`
- add & update tests
- add & update documentation
+ [README](https://github.com/tqdm/tqdm#tqdm)
+ [examples/](https://github.com/tqdm/tqdm/tree/master/examples)
- update CI framework
---
- fixes #885
- closes #880
- fixes #840
- fixes #480
- fixes #402

next release v4.42.0

---

.meta/.readme.rst
.travis.yml
.zenodo.json
README.rst
tqdm/std.py

- support `pandas==1.0.0` (#780, #555)
- minor metadata updates
- minor CI test update

next release v4.42.1

---

tqdm/contrib/concurrent.py

do not call len on iterable

---

.meta/.snapcraft.yml
DEMO.ipynb
examples/paper.md

```python
```
---
As discussed in https://github.com/tqdm/tqdm/issues/895 and updated in https://github.com/tqdm/tqdm/pull/897, and confirmed by the original author and namer in https://github.com/tqdm/tqdm/issues/887#issuecomment-578633295:
> Regarding history, I first wrote tqdm where I worked, at about 2006. Iterators where pretty new, and I really liked the …

Update Arabic spelling

---

tqdm/_utils.py

- fixes #927
- continues #924 <- #918

fix import error => deprecation

---

.meta/.readme.rst
README.rst
tqdm/notebook.py
tqdm/std.py

- doesn't `close()` on notebooks since the user may have a shared bar which they'd like to `reset()` instead
+ [x] document use of a shared `notebook` bar
- fixes (partially) #548

Exceptions

---

.meta/.readme.rst
DEMO.ipynb
Makefile
README.rst
tqdm/notebook.py
tqdm/std.py
tqdm/tests/tests_tqdm.py

- propagate and `close()` on exceptions (#926 <- #548)
- fix nested `clear()`
- rework nested `close()` (#930 <- #924 <- #918, #677)
+ reduces screen flicker/blank space at the cost of ordering
- add and update tests

next release v4.45.0

---

tqdm/std.py

```
>>> print(tqdm.__version__, sys.version, sys.platform)
4.45.0 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] win32
```
A lock is never released by `tqdm.external_write_mode` context manager if an exception occurs within.
Example: if a bar.write() raises as exception while writing to the file handler (for example, writing a text that is unsupported by the terminal might raise such an error while encoding/decoding the string) the lock is never release.
----
+ [x] exception-raising fix
```python
```
[source website]: …

Fix: release lock if an exception occurs within `tqdm.external_write_mode`

---

.coveragerc
.meta/.readme.rst
.meta/.snapcraft.yml
.meta/mkcompletion.py
.meta/mkdocs.py
CONTRIBUTING.md
DEMO.ipynb
MANIFEST.in
Makefile
README.rst
examples/tqdm_requests.py
examples/tqdm_wget.py
setup.py
tqdm/cli.py
tqdm/completion.sh
tqdm/contrib/telegram.py
tqdm/std.py
tqdm/tests/tests_main.py
tqdm/tqdm.1

- add `contrib.telegram` #949 <- #948
- add `bash` tab completion and `--comppath` #946, #947 <- #858
- fix exception safety in `external_write_mode` #940
- add `requests` examples (#242)
----
- closes #949
+ fixes #948
+ related #509
- closes #946
+ closes #947
+ fixes #858
- closes #940
+ related #548
- fixes #242

Next release v4.46.0

---

.github/workflows/bench.yml
.github/workflows/comment-bot.yml
.github/workflows/post-release.yml
.meta/.readme.rst
.travis.yml
CONTRIBUTING.md
Makefile
README.rst
asv.conf.json
benchmarks/README.md
benchmarks/benchmarks.py
examples/async_coroutines.py
examples/coroutine_pipe.py
tqdm/_tqdm_pandas.py
tqdm/asyncio.py
tqdm/auto.py
tqdm/autonotebook.py
tqdm/contrib/bells.py
tqdm/contrib/discord.py
tqdm/contrib/telegram.py
tqdm/gui.py
tqdm/notebook.py
tqdm/std.py
tqdm/tests/py37_asyncio.py
tqdm/tests/tests_asyncio.py
tqdm/tests/tests_tqdm.py

- add `tqdm.asyncio` (#1004, #772, #91 <- #65)
+ supports async iterables (`async for row in tqdm(iterable)`)
+ supports iterables
+ supports `coroutine.send` (`tqdm(coroutine).send`)
+ add `as_completed` wrapper (`for f in tqdm.as_completed(fs)`)
- reduce `contrib.discord` logging verbosity
- fix potential `pandas()` modifying `**kwargs` bug
+ add missing inline docstrings
+ update contributing notes
+ update readme
+ add to `examples/` folder
* async_coroutines
* coroutine_pipe
- add tests
+ add benchmark tests against popular alternative libraries
+ test new functionality
+ more thorough `miniters` test (#1003)
- misc framework updates
+ tidy changelog helper
+ add helper bots
* comment-bot `/tag`
* post-release-bot
- wiki updater
- website updater
* benchmark …

next release v4.48.0

---

tqdm/auto.py

in case this is a really obvious bug , this should fix #1028

fix version detection in auto.py

---

appveyor.yml
tests/tests_tqdm.py
tox.ini

[![Build status](https://ci.appveyor.com/api/projects/status/5atuybn97nvk5lir?svg=true)](https://ci.appveyor.com/project/casperdcl/tqdm)

add appveyor.yml

---

.github/workflows/test.yml
setup.cfg

- drop `py3.4` (no longer tested)
- misc CI updates
+ update `snap` build & deploy method
+ bot releases

next release v4.54.1

---

CONTRIBUTING.md
tqdm/std.py

- fix `(Rolling|Expanding).progress_apply()` on `pandas==1.2.0` (#1106)
- minor documentation updates
----
- fixes #1106

next release v4.55.1

---

.meta/.readme.rst
README.rst
environment.yml
tests/tests_gui.py
tests/tests_rich.py
tests/tests_tk.py
tox.ini
tqdm/gui.py
tqdm/notebook.py
tqdm/rich.py
tqdm/tk.py

- add `tqdm.tk` (#1006)
- add `tqdm.rich`
- minor formatting improvements for `tqdm.gui`
- fix `display()` inheritance/override
- add tests
- add documentation
----
- closes #1006

next release v4.56.0

---

.github/FUNDING.yml
.github/workflows/test.yml
.mailmap
.meta/.readme.rst
.meta/requirements-build.txt
.meta/requirements-test.txt
CONTRIBUTING.md
Makefile
README.rst
benchmarks/README.md
environment.yml
setup.cfg
tests/py37_asyncio.py
tests/tests_dask.py
tests/tests_keras.py
tox.ini
tqdm/asyncio.py
tqdm/auto.py
tqdm/completion.sh
tqdm/dask.py
tqdm/gui.py
tqdm/keras.py
tqdm/notebook.py
tqdm/rich.py
tqdm/std.py
tqdm/tqdm.1

- add `tqdm.dask.TqdmCallback` (#1079, #279 <- #278)
- add `asyncio.gather()` (#1136)
- add tests
- misc documentation updates
+ update contributing guide
----
- closes #1136
- fixes #278
- replaces/closes #279

next release: v4.59.0

---

.github/FUNDING.yml
.github/workflows/test.yml
.gitignore
.pre-commit-config.yaml
tests/py37_asyncio.py
tqdm/asyncio.py
tqdm/utils.py

- `asyncio.gather` API consistency with stdlib (#1212)
- fix shutdown exception (#1198)
- misc build framework updates
- add [GH Sponsors](https://github.com/sponsors/tqdm/dashboard/tiers?frequency=one-time) & [merch](https://tqdm.github.io/merch) links
----
- closes #1212
- fixes #1198

next release v4.62.0

---

.meta/.readme.rst
CONTRIBUTING.md
README.rst

Let's not make people read the contributing guide in the hard mode, shall we.

Link to non-plain CONTRIBUTING.md in README

---

tqdm/contrib/telegram.py

- fixes #1220
- fixes #1076
- replaces/closes #1221

`contrib.telegram`: gracefully handle creation rate limit

---

.github/workflows/post-release.yml
.github/workflows/test.yml
.meta/mkdocs.py
.meta/requirements-test.txt
.pre-commit-config.yaml
LICENCE
Makefile
environment.yml
examples/7zx.py
setup.cfg
tests/tests_contrib.py
tests/tests_itertools.py
tests/tests_perf.py
tests/tests_tqdm.py
tox.ini
tqdm/_monitor.py
tqdm/_utils.py
tqdm/rich.py
tqdm/std.py

- fix minor typo
- minor example fix
- misc tidying & refactoring
- misc build & test framework updates
+ update dependencies
+ update linters
+ update docs deployment branches
+ test forks
+ tidy OS & Python version tests
+ bump primary python version 3.7 => 3.8

next release v4.62.3

---

tqdm/cli.py
tqdm/contrib/itertools.py
tqdm/notebook.py
tqdm/std.py

next release v4.63.1

---

tqdm/notebook.py

- fixes #1310 (& fixes #1359)
- fixes #1360

fix jupyterlab display

---

.github/workflows/test.yml
tests_notebook.ipynb
tqdm/notebook.py

- support ipywidgets>=8
+ fix jupyter lab display
+ update notebook tests
---
- fixes #1310, closes #1364

next release v4.64.1

---

.github/workflows/check.yml
.github/workflows/comment-bot.yml
.github/workflows/post-release.yml
.github/workflows/test.yml
.meta/.readme.rst
.meta/nbval.ini
.pre-commit-config.yaml
LICENCE
Makefile
README.rst
environment.yml
tests/tests_keras.py
tests/tests_pandas.py
tests/tests_perf.py
tests/tests_tqdm.py
tqdm/keras.py
tqdm/notebook.py
tqdm/std.py
tqdm/utils.py

- `pandas`: add `DataFrame.progress_map`
- fix `format_num` negative fractions missing leading zero (#1549 <- #1548)
- `notebook`: fix HTML padding (#1506)
- `keras`: fix resuming training when `verbose>=2` (#1508)
- misc: fix Python 3.12 `DeprecationWarning` on `import` (#1519)
- linting: use f-strings (#1549)
- tests
+ fix `pandas` warnings
+ fix `asv` (https://github.com/airspeed-velocity/asv/issues/1323)
+ fix macos `notebook` docstring indentation
- CI: bump actions (#1549)
---
- fixes #1548
- closes #1506
- closes #1508
- closes #1519

next release v4.66.2

---

.github/workflows/comment-bot.yml
.github/workflows/test.yml
.meta/.readme.rst
.meta/mksnap.py
.pre-commit-config.yaml
DEMO.ipynb
Makefile
README.rst
examples/paper.bib
pyproject.toml
tox.ini
tqdm/cli.py

- cli: zip-safe `--manpath`, `--comppath`
- docs: update URLs
- misc framework updates
+ fix `pytest` `DeprecationWarning`
+ fix `snapcraft` build
+ fix `nbval` `DeprecationWarning`
+ update & tidy workflows
+ bump pre-commit

misc minor updates
